name: CDN Code Purge
on: 
  push:
    branches:
      - uat
      - dev
      - stage
      - pprod
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Info
      run: |
        echo "Code pushed on branch: ${{ github.ref_name }}"
  build-vars:
    runs-on: ubuntu-latest
    outputs:
      ENV: ${{ steps.upperenv.outputs.uppercase }}
      CDN_PURGE_BRANDS_KEY: ${{ steps.setvars.outputs.CDN_PURGE_BRANDS_KEY }}
      BRANCH: ${{github.ref_name}}
    steps:
      - name: set env prod
        if: ${{ github.ref_name == 'stage' || github.ref_name == 'pprod' }}
        id: setenvprod
        run: |
          echo "ENV=PROD" >>$GITHUB_ENV
      - name: set env non-prod
        if: ${{ github.ref_name == 'uat' || github.ref_name == 'dev' }}
        id: setenvnonprod
        run: |
          echo "ENV=${{ github.ref_name }}" >>$GITHUB_ENV
      - id: upperbranch
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{github.ref_name}}
      - name: Set CDN Purge Key
        id: setvars
        run: |
          echo ${{ steps.upperbranch.outputs.uppercase}}
          echo "CDN_PURGE_BRANDS_KEY=${{ format('{0}_CDN_PURGE_BRANDS', steps.upperbranch.outputs.uppercase ) }}" >>$GITHUB_OUTPUT
  cdn-purgecode:
    needs: build-vars
    runs-on: ubuntu-latest
    strategy:
      matrix:
        brand: ${{ fromJSON(vars[needs.build-vars.outputs.CDN_PURGE_BRANDS_KEY]) }}
    steps:
      - name: Echo Vars
        run: |
          echo "ENV: ${{ needs.build-vars.outputs.ENV }}"
          echo "Brand ${{ matrix.brand }}"
          echo "BRANCH: ${{needs.build-vars.outputs.BRANCH}}"
      - name: uppercase
        id: upperbrand
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{matrix.brand}}
      - name: uppercase
        id: lowerenv
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{needs.build-vars.outputs.BRANCH}}
      - name: Format Keys
        id: formatkeys
        run: |
          echo "FASTLY_SERVICE_ID_KEY=${{ format('{0}_{1}_FASTLY_SERVICE_ID', steps.upperbrand.outputs.uppercase, needs.build-vars.outputs.ENV ) }}" >>$GITHUB_ENV
          echo "FASTLY_API_KEY_KEY=${{ format('{0}_{1}_FASTLY_API_KEY', steps.upperbrand.outputs.uppercase, needs.build-vars.outputs.ENV ) }}" >>$GITHUB_ENV
      - name: Purge CDN Code
        id: purgecdncode
        env:
          FASTLY_SERVICE_ID: ${{ secrets[env.FASTLY_SERVICE_ID_KEY] }}
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ format('https://api.fastly.com/service/{0}/purge/{1}--eds-web--alshaya-axp_code', env.FASTLY_SERVICE_ID,  steps.lowerenv.outputs.lowercase) }}
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "Fastly-Key": "${{ secrets[env.FASTLY_API_KEY_KEY] }}", "Accept": "application/json"}'
      - name: Show Response
        run: |
          echo ${{ steps.purgecdncode.outputs.response }}
          echo ${{ steps.purgecdncode.outputs.headers }}
          echo ${{ steps.purgecdncode.outputs.status }}
