name: CDN Purge on Resource Published/Unpublished
on: 
  repository_dispatch:
    types:
      - resource-published
      - resource-unpublished
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Info
      run: |
        echo "Status: ${{ github.event.client_payload.status }}"
        echo "Payload: ${{ toJson(github.event.client_payload) }}"
  build-vars:
    runs-on: ubuntu-latest
    outputs:
      BRAND: ${{ steps.setvars.outputs.BRAND }}
      ENV: ${{ steps.setvars.outputs.ENV }}
      MARKET: ${{ steps.setvars.outputs.MARKET }}
      CDN_PURGE_MARKETS: ${{ steps.setvars.outputs.CDN_PURGE_MARKETS }}
      CDN_DOMAINS_KEY: ${{ steps.setvars.outputs.CDN_DOMAINS_KEY }}
      CDN_DOMAINS_ALL_KEY: ${{ steps.setvars.outputs.CDN_DOMAINS_ALL_KEY }}
      FASTLY_API_KEY_KEY: ${{ steps.setvars.outputs.FASTLY_API_KEY_KEY }}
      matrix: ${{ steps.setvars.outputs.CDN_PURGE_MARKETS }}
    steps:
      - name: Format brand
        id: formatbrand
        uses: frabert/replace-string-action@v2
        with:
          pattern: '([a-zA-Z0-9]*)\-([a-zA-Z0-9]*)\-([a-zA-Z0-9]*)'
          string: ${{ github.event.client_payload.site }}
          replace-with: '$1'
      - name: Format env
        id: formatenv
        uses: frabert/replace-string-action@v2
        with:
          pattern: '([a-zA-Z0-9]*)\-([a-zA-Z0-9]*)\-([a-zA-Z0-9]*)'
          string: ${{ github.event.client_payload.site }}
          replace-with: '$2'
      - name: Format market
        id: formatmarket
        uses: frabert/replace-string-action@v2
        with:
          pattern: '([a-zA-Z0-9]*)\-([a-zA-Z0-9]*)\-([a-zA-Z0-9]*)'
          string: ${{ github.event.client_payload.site }}
          replace-with: '$3'
      - name: uppercase
        id: upperbrand
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{steps.formatbrand.outputs.replaced}}
      - id: upperenv
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{steps.formatenv.outputs.replaced}}
      - id: uppermarket
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{steps.formatmarket.outputs.replaced}}
      - name: Format Keys
        id: formatkeys
        run: |
          echo "CDN_PURGE_MARKETS_KEY=${{ format('{0}_{1}_CDN_PURGE_MARKETS', steps.upperbrand.outputs.uppercase, steps.upperenv.outputs.uppercase ) }}" >>$GITHUB_ENV
      - name: Set BRAND, ENV, MARKET
        id: setvars
        run: |
          echo "BRAND=${{ steps.upperbrand.outputs.uppercase }}" >> $GITHUB_OUTPUT
          echo "ENV=${{ steps.upperenv.outputs.uppercase }}" >> $GITHUB_OUTPUT
          echo "MARKET=${{ steps.uppermarket.outputs.uppercase }}" >> $GITHUB_OUTPUT
          echo "CDN_PURGE_MARKETS=${{ vars[env.CDN_PURGE_MARKETS_KEY] }}" >> $GITHUB_OUTPUT
          echo "CDN_DOMAINS_KEY=${{ format('{0}_{1}_CDN_DOMAINS', steps.upperbrand.outputs.uppercase, steps.upperenv.outputs.uppercase ) }}" >>$GITHUB_OUTPUT
          echo "CDN_DOMAINS_ALL_KEY=${{ format('{0}_{1}_CDN_DOMAINS_ALL', steps.upperbrand.outputs.uppercase, steps.upperenv.outputs.uppercase ) }}" >>$GITHUB_OUTPUT
          echo "FASTLY_API_KEY_KEY=${{ format('{0}_{1}_FASTLY_API_KEY', steps.upperbrand.outputs.uppercase, steps.upperenv.outputs.uppercase ) }}" >>$GITHUB_OUTPUT
  cdn-purge:
    if: ${{ !endsWith(github.event.client_payload.path, 'placeholders.json') && !endsWith(github.event.client_payload.site, 'global') }}
    needs: build-vars
    runs-on: ubuntu-latest
    strategy:
      matrix:
        domain: ${{ fromJSON(vars[needs.build-vars.outputs.CDN_DOMAINS_KEY])[needs.build-vars.outputs.MARKET] }}
    steps:
      - name: Echo Vars
        run: |
          echo "BRAND : ${{ needs.build-vars.outputs.BRAND }}"
          echo "ENV: ${{ needs.build-vars.outputs.ENV }}"
          echo "MARKET: ${{ needs.build-vars.outputs.MARKET }}"
          echo "CDN_PURGE_MARKETS: ${{ needs.build-vars.outputs.CDN_PURGE_MARKETS }}"
          echo "CDN_DOMAINS_KEY: ${{ needs.build-vars.outputs.CDN_DOMAINS_KEY }}"
          echo "CDN_DOMAINS_ALL_KEY: ${{ needs.build-vars.outputs.CDN_DOMAINS_ALL_KEY }}"
          echo "FASTLY_API_KEY_KEY: ${{ needs.build-vars.outputs.FASTLY_API_KEY_KEY }}"
          echo "CDN_DOMAINS_ALL: ${{ vars[needs.build-vars.outputs.CDN_DOMAINS_ALL_KEY] }}"
      - name: Format path
        id: format
        uses: frabert/replace-string-action@v2
        with:
          pattern: '\.md'
          string: ${{ github.event.client_payload.path }}
          replace-with: ''
      - name: Purge CDN Docs (except Placeholders)
        if: ${{ contains(needs.build-vars.outputs.CDN_PURGE_MARKETS, needs.build-vars.outputs.MARKET) }}
        id: purgecdn
        env:
          FASTLY_API_KEY: ${{ secrets[needs.build-vars.outputs.FASTLY_API_KEY_KEY] }}
          CDN_DOMAINS: ${{vars[needs.build-vars.outputs.CDN_DOMAINS_KEY]}}
          CDN_DOMAINS_ALL: ${{vars[needs.build-vars.outputs.CDN_DOMAINS_ALL_KEY]}}
          MARKET: ${{ needs.build-vars.outputs.MARKET }}
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ format('https://api.fastly.com/purge/{0}{1}', matrix.domain,  steps.format.outputs.replaced) }}
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "Fastly-Key": "${{ env.FASTLY_API_KEY }}", "Accept": "application/json"}'
      - name: Show Response
        run: |
          echo ${{ steps.purgecdn.outputs.response }}
          echo ${{ steps.purgecdn.outputs.headers }}
          echo ${{ steps.purgecdn.outputs.status }}
  cdn-purgeplaceholders:
    if: ${{ endsWith(github.event.client_payload.path, 'placeholders.json') && endsWith(github.event.client_payload.site, 'global') }}
    needs: build-vars
    runs-on: ubuntu-latest
    strategy:
      matrix:
        domain: ${{ fromJSON(vars[needs.build-vars.outputs.CDN_DOMAINS_ALL_KEY]) }}
    steps:
      - name: Echo Vars
        run: |
          echo "BRAND : ${{ needs.build-vars.outputs.BRAND }}"
          echo "ENV: ${{ needs.build-vars.outputs.ENV }}"
          echo "MARKET: ${{ needs.build-vars.outputs.MARKET }}"
          echo "CDN_PURGE_MARKETS: ${{ needs.build-vars.outputs.CDN_PURGE_MARKETS }}"
          echo "CDN_DOMAINS_KEY: ${{ needs.build-vars.outputs.CDN_DOMAINS_KEY }}"
          echo "CDN_DOMAINS_ALL_KEY: ${{ needs.build-vars.outputs.CDN_DOMAINS_ALL_KEY }}"
          echo "FASTLY_API_KEY_KEY: ${{ needs.build-vars.outputs.FASTLY_API_KEY_KEY }}"
          echo "CDN_DOMAINS_ALL: ${{ vars[needs.build-vars.outputs.CDN_DOMAINS_ALL_KEY] }}"
      - name: echo domain
        run: |
          echo "Domain: ${{ matrix.domain }}"
      - name: Purge CDN JSON
        id: purgecdnjson
        env:
          FASTLY_API_KEY: ${{ secrets[needs.build-vars.outputs.FASTLY_API_KEY_KEY] }}
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ format('https://api.fastly.com/purge/{0}{1}', matrix.domain,  github.event.client_payload.path) }}
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json", "Fastly-Key": "${{ env.FASTLY_API_KEY }}", "Accept": "application/json"}'
      - name: Show Response
        run: |
          echo ${{ steps.purgecdnjson.outputs.response }}
          echo ${{ steps.purgecdnjson.outputs.headers }}
          echo ${{ steps.purgecdnjson.outputs.status }}
