name: Core Framework Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    
permissions:
  contents: read
  pull-requests: write  # ✅ Ensures PR labels can be modified

jobs:
  check-core-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            blocks/*/*.css
            blocks/*/*.js
            blocks/*/slots/*.js
            scripts/**/*.js
            styles/*.css
            templates/*/*.css
            templates/*/*.js
            theme-tools/*.*
            tools/**/*.*
            react-app/api/**
            react-app/context/**
            react-app/library/**
            react-app/shared/**
            react-app/store/**
            react-app/utils/**
            react-app/app/*/*.css
            react-app/app/*/*.js
            react-app/app/*/components/**

      - name: Check if core files were changed
        id: check-core
        run: |
          if [[ "${{ steps.changed-files.outputs.any_changed }}" == "true" ]]; then
            echo "core_files_changed=true" >> $GITHUB_OUTPUT
            echo "core_files=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_OUTPUT
          else
            echo "core_files_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Add label to PR
        if: steps.check-core.outputs.core_files_changed == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['CORE FRAMEWORK']
            })

      - name: Add reviewers to PR
        if: steps.check-core.outputs.core_files_changed == 'true' && env.CORE_REVIEWERS != ''
        uses: actions/github-script@v6
        env:
          CORE_REVIEWERS: ${{ env.CORE_REVIEWERS }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const coreReviewers = process.env.CORE_REVIEWERS.split(',').map(r => r.trim());
            
            // Get PR details including current reviewers and PR author
            const { data: prData } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            // Get current reviewers
            const currentReviewers = prData.requested_reviewers ? 
              prData.requested_reviewers.map(reviewer => reviewer.login) : [];
            
            // Get PR author
            const prAuthor = prData.user.login;
            
            // Filter out reviewers who are already on the PR or who raised the PR
            const reviewersToAdd = coreReviewers.filter(reviewer => 
              !currentReviewers.includes(reviewer) && reviewer !== prAuthor
            );
            
            if (reviewersToAdd.length > 0) {
              console.log(`Adding reviewers: ${reviewersToAdd.join(', ')}`);
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                reviewers: reviewersToAdd
              });
            } else {
              console.log('No new reviewers to add (all core reviewers are already added or are the PR author)');
            }

      - name: Format core files for comment
        if: steps.check-core.outputs.core_files_changed == 'true'
        id: format-files
        run: |
          FILES="${{ steps.check-core.outputs.core_files }}"
          FORMATTED_FILES=""
          
          # Convert space-separated list to markdown bullet points
          for FILE in $FILES; do
            FORMATTED_FILES="${FORMATTED_FILES}- \`${FILE}\`\n"
          done
          
          # Escape the formatted files for GitHub Actions
          FORMATTED_FILES="${FORMATTED_FILES//'%'/'%25'}"
          FORMATTED_FILES="${FORMATTED_FILES//$'\n'/'%0A'}"
          FORMATTED_FILES="${FORMATTED_FILES//$'\r'/'%0D'}"
          
          echo "formatted_files=${FORMATTED_FILES}" >> $GITHUB_OUTPUT

      - name: Add comment to PR
        if: steps.check-core.outputs.core_files_changed == 'true'
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ## Core Framework Files Detected
            
            This PR contains changes to the following core framework files:
            
            ${{ steps.format-files.outputs.formatted_files }}
            
            This PR has been labeled as a "CORE FRAMEWORK" change and appropriate reviewers have been notified. 